### ISSUE TITLE
[Q] Dynamic generation of only required tiles?

### ISSUE THREAD

**Issue by peterlitvak** [usnistgov/pyramidio#3]
Have you considered making dynamic generation of only the required tiles a feature of the component? This could be very useful if this component is used as part of an implementation of an end point for the UI (e.g. openseadragon) for handling "unlimited" size images.

**Comment by avandecreme** [comment]
Do you mean that you would like to generate the tiles on the fly when the client request them?

I don't see how that would scale with big images. For example, if the user request the level 0, the whole image has to be read and down-sampled. That would take to much time (and memory) to do it as part of a web service.

**Comment by peterlitvak** [comment]
you are correct, that question came from my poor understanding of how DZI is produced, I've educated myself now :)

**Comment by avandecreme** [comment]
You might be interested in [iipsrv](https://github.com/ruven/iipsrv).
I never tested it but they claim to support such functionality.

**Comment by peterlitvak** [comment]
Very interesting, thank you!
