### ISSUE TITLE
What Maven repositories is the pyramidio published to?

### ISSUE THREAD

**Issue by peterlitvak** [usnistgov/pyramidio#5]
Just noticed that it is not in the maven central

**Comment by avandecreme** [comment]
I just made a request to OSSRH.
In the mean time you may be able to use https://jitpack.io/

**Comment by peterlitvak** [comment]
Nice! Thank you!

**Comment by avandecreme** [comment]
And published to maven central: https://repo1.maven.org/maven2/gov/nist/isg/

**Comment by peterlitvak** [comment]
Thank you
